-- Seed data GUIM Story — angkatan 12, 13, 14 (lanjutan dari 0003 [angkatan 1-10] dan
-- 0006 [angkatan 11]).
--
-- Sumber: "Output dan Outcome Gerakan UI Mengajar 12-14" (104 hal., Olahan Penulis 2025),
-- ada di docs/riset_guim11-15/. Ini laporan output-outcome pasca-aksi (BAB I profil,
-- BAB II program logic + temuan/rekomendasi + jumlah penerima manfaat, BAB III M&E,
-- BAB IV luaran/HKI/publikasi, BAB V kemitraan & dana) — jauh lebih lengkap dari
-- proposal pra-aksi yang jadi sumber angkatan 11.
--
-- Pemetaan field (konsisten dengan seed sebelumnya):
--   inovasi                 -> program/kegiatan khas angkatan tsb. di titik aksi
--   pembaharuan             -> capaian & kebaruan menonjol (diambil dari bagian "Outputs")
--   evaluasi_lesson_learned -> temuan umum, rekomendasi, dan hasil monitoring & evaluation
--
-- CATATAN ANGKA (penting, jangan diubah tanpa cek sumber):
--   * jumlah_panitia diisi dari kolom "Jumlah Panitia" tabel "Jumlah Penerima Manfaat".
--     Di sumber, kolom itu sebenarnya menghitung SELURUH fungsionaris yang diterjunkan
--     ke titik aksi (panitia + pengajar + tim mobile) — GUIM 13 mengonfirmasi angkanya
--     sebagai "90 IKM UI terlibat langsung ... tersebar ke 5 sekolah sasaran".
--     Karena itu jumlah_pengajar sengaja NULL untuk ketiga angkatan supaya tidak
--     dihitung ganda di chart /cerita-guim. (GUIM 12 menyebut "30 pengajar" di BAB I;
--     fakta itu disimpan di gambaran_umum, bukan di kolom angka.)
--   * jumlah_siswa GUIM 13 = 372 (jumlah baris tabel 2.2.4 dan angka total tabelnya).
--     Bagian "Outputs" menulis 373 — selisih 1, sumber tidak konsisten; dipakai 372.
--   * jumlah_desa hanya diisi untuk GUIM 12 ("lima sekolah dasar di lima desa terpilih").
--     Sumber tidak menyebut jumlah desa untuk GUIM 13 dan 14 -> NULL (keputusan ID-008).
--   * Tanggal aksi GUIM 13: BAB 1.2.1 menulis 4 Januari - 2 Februari 2024, BAB 1.2.2
--     menulis 8 Januari - 2 Februari 2025. Tahun 2024 yang benar (kepengurusan Juni 2023 -
--     Juli 2024, publikasi Tempo/Jawa Pos Januari 2024); "2025" di 1.2.2 salah ketik.
--     Dipakai versi 1.2.1 dan tanggal mulai ditulis apa adanya.
--   * GUIM 14: BAB 1.3.2 dan tabel 2.4.4 sama-sama menunjukkan 6 SD di 5 kecamatan
--     (Bogorejo punya 2 sekolah). Narasi Survei 1 menyebut "6 kecamatan" dan
--     "SDN 2 Bogorejo" — tidak konsisten; dipakai tabel titik intervensi (SDN 3 Bogorejo).
--
-- Status: 'draft'. Angkatan 11 juga masih draft, dan angka kumulatif di
-- src/lib/guim-stats.ts (angkatan: 10) serta copy "baru 10 angkatan terdokumentasi" di
-- /about dan /cerita-guim belum diperbarui. Publish setelah itu disinkronkan.

insert into public.guim_story (
  slug, angkatan, nama_angkatan, kabupaten, provinsi, tahun_pelaksanaan, tema, tagline, nilai,
  gambaran_umum, latar_belakang,
  timeline_pra_aksi, timeline_aksi, timeline_pasca_aksi,
  titik_pelaksanaan, inovasi, pembaharuan, evaluasi_lesson_learned,
  jumlah_panitia, jumlah_pengajar, jumlah_siswa, jumlah_guru, jumlah_sd, jumlah_desa, jumlah_kecamatan,
  status
) values

(
  'guim-12', 12, 'GUIM 12', 'Kabupaten Nganjuk', 'Jawa Timur', 'Januari - Juli 2023',
  'Berbagi Warna Melukis Cita', null, null,
  'GUIM 12 melaksanakan aksinya di Kabupaten Nganjuk, Provinsi Jawa Timur, dipilih karena masih rendahnya angka keberlanjutan pendidikan dan memprihatinkannya kondisi sekolah di wilayah tersebut (data BPS dan Kemdikbud). Kegiatan utamanya adalah mengirimkan 30 pengajar terbaik ke lima sekolah dasar di lima desa terpilih; para pengajar mengajar bersama guru kelas sambil menerapkan metode belajar yang menyenangkan dan berbagi inspirasi kepada setiap murid. Aksi berlangsung 7 Januari - 2 Februari 2023, hampir satu bulan penuh, dengan rangkaian kegiatan inklusif yang melibatkan banyak pihak: Kegiatan Belajar Mengajar, kelas informal, Rumah Pelangi, Pelatihan Guru, hingga Festival Rakyat.',
  '"Berbagi warna, melukis cita" menggambarkan berbagai hal yang dibagikan dan didapatkan oleh panitia, pengajar, anak-anak, masyarakat, serta stakeholder lain yang tergabung dalam gerakan ini. GUIM 12 berangkat dari semangat untuk ikut menjadi bagian dari solusi kesenjangan dan keberlanjutan pendidikan di Indonesia lewat aksi nyata, dengan harapan mampu menanamkan pendidikan karakter, membangun semangat murid untuk terus belajar dan melanjutkan sekolah, serta menumbuhkan cita-cita.',
  ARRAY['Survei 0 (data sekunder) untuk memilih kabupaten titik aksi — pertimbangan APM SD 87,98%, IPM 71,97, UKG 58,63, Angka Melek Huruf 92,13, tren kriminalitas menurun, dan tingkat vaksinasi Covid-19 90,47%','Survei 1: kunjungan ke 17 sekolah di 7 kecamatan (Jatikalen, Ngluyu, Lengkong, Gondang, Pace, Rejoso, Sawahan), perizinan Kesbangpol-kecamatan-desa, serta pengumpulan data kuantitatif dan kualitatif sekolah','Survei 1 menghasilkan 5 kecamatan terpilih beserta rekomendasi sekolah untuk survei 2','Survei 2: pengumpulan data primer lewat wawancara stakeholder, guru, dan masyarakat, FGD dengan guru-wali murid, audiensi dengan pihak sekolah, serta pencarian rumah panitia dan pengajar','Rekrutmen terbuka: 67 mahasiswa UI mendaftar sebagai panitia, 237 mendaftar sebagai calon pengajar (108 mengumpulkan berkas)'],
  ARRAY['Aksi mengajar di 5 SD Kabupaten Nganjuk: 7 Januari - 2 Februari 2023','Kegiatan Belajar Mengajar efektif selama 3 minggu di 5 titik, dengan mekanisme team teaching bersama guru wali kelas','Home Visit: kunjungan ke rumah siswa untuk mewawancarai orang tua/wali soal latar belakang keluarga dan kepedulian terhadap pendidikan anak','Teacher Visit: kunjungan pengajar dan divisi ED ke rumah wali kelas','Teacher Conference dan Parents Conference: evaluasi gabungan dengan guru, serta pembagian laporan hasil belajar kepada orang tua','Pelatihan Guru untuk menunjang kemampuan mengajar','Kelas informal: Kelas Inspirasi (pengenalan profesi), Kelas Pendidikan Diri & Tubuh Sehat Ceria, Kelas Kenali Nusantara dan Mari Nyeni','Rumah Pelangi: revitalisasi pojok baca/perpustakaan sekolah','Bincang Orang Tua: diskusi panitia bersama orang tua siswa di tiap titik','Festival Rakyat: penutup seluruh rangkaian di titik aksi, mengundang pihak sekolah dan tokoh masyarakat'],
  ARRAY['Penyusunan laporan rekomendasi per titik untuk diadvokasikan ke pemangku kebijakan','Publikasi kegiatan di media lokal dan nasional (ANTARA News, Kumparan, Diskominfo Nganjuk, Pendidikan.id, dan lainnya)','Pendaftaran HKI untuk infografis dan after movie GUIM 12','Monitoring dan Evaluation: 23-27 Juli 2023, enam bulan setelah masa aksi'],
  '[{"nama":"SDN 2 Sugihwaras","kecamatan":"Ngluyu"},{"nama":"SDN 1 Tritik","kecamatan":"Rejoso"},{"nama":"SDN 1 Joho","kecamatan":"Pace"},{"nama":"SDN Bendolo","kecamatan":"Sawahan"},{"nama":"SDN 2 Begendeng","kecamatan":"Jatikalen"}]'::jsonb,
  ARRAY['Kolaborasi dengan CoLearn dan KIPIN (Kios Pintar) untuk mengenalkan potensi edutech dan digitalisasi sekolah di titik aksi','Rumah Pelangi sebagai revitalisasi pojok baca dan perpustakaan sekolah di setiap titik','Rangkaian kelas informal bertema pengenalan profesi, pendidikan diri, kesehatan tubuh, kecintaan tanah air, dan seni','Kolom "Aku Bisa Menjadi" di rapor siswa sebagai penanda pengenalan potensi dan cita-cita','Bincang Orang Tua dan Parents Conference untuk menarik orang tua masuk ke dalam proses belajar anak','Budaya tepuk-tepuk apresiasi yang ditanamkan di kelas selama masa aksi'],
  ARRAY['96,8% panitia dan pengajar berpartisipasi aktif; 91 dari 93 fungsionaris (97,8%) merasa menerima manfaat dengan rata-rata skor 6','100% panitia dan pengajar berhasil sampai di titik aksi dan kembali ke kampus UI Depok dengan selamat','Pengajar melaksanakan 100% KBM selama periode aksi','89,6% siswa dapat mengikuti dan memahami KBM dengan baik','100% anak usia SD di titik aksi mengenali potensi dirinya; Kelas Inspirasi terlaksana 100% di seluruh titik','Skor kepuasan kuesioner kebermanfaatan 5,7-5,8 dari 6 untuk aspek semangat belajar siswa, motivasi belajar, dan kepedulian masyarakat terhadap pendidikan','Berhasil bekerja sama dengan 53 stakeholder eksternal','Total dana terkumpul Rp200.900.921 (Dirmawa UI, sponsor BNI-Mandiri Capital-PT Marga Harjaya Infrastruktur, serta merchandise dan open donation)'],
  ARRAY['Temuan: banyak siswa kesulitan literasi dasar — mengenal huruf dan membaca — bahkan hingga kelas atas','Temuan: keterlibatan orang tua dalam proses pendidikan masih rendah','Temuan: metode mengajar guru cenderung monoton dan kurang menjangkau semua siswa secara merata; fasilitas belajar terbatas dan kedisiplinan guru menjadi tantangan','Rekomendasi pemerintah daerah: program literasi dasar terintegrasi untuk kelas rendah, pelatihan berkala metode pembelajaran aktif-inklusif bagi guru, dan penambahan dana operasional perbaikan fasilitas sekolah','Rekomendasi sekolah: perkuat komunikasi dengan orang tua lewat pertemuan rutin dan home visit, tingkatkan kedisiplinan serta profesionalisme guru, dan jaga fasilitas literasi seperti Rumah Pelangi','Rekomendasi masyarakat dan orang tua: aktif mendampingi anak belajar di rumah dan menumbuhkan kesadaran bahwa pendidikan adalah proses jangka panjang','Monev Juli 2023: orang tua semakin sering menemani anak belajar dan menaruh perhatian pada kegiatan non-akademis, meski masih ada perbedaan pandangan soal melanjutkan pendidikan tinggi','Monev Juli 2023: guru menilai siswa kelas kecil lebih aktif menjawab pertanyaan, dan guru kelas besar makin konsisten menerapkan personal approach','Monev Juli 2023: siswa lebih mandiri mengerjakan PR, motivasi dan kepercayaan diri meningkat, budaya tepuk-tepuk apresiasi bertahan','Pelajaran keberlanjutan: menurut orang tua, dampak langsung GUIM bertahan sekitar 2 minggu sebelum sebagian kondisi kembali seperti semula — di beberapa titik perpustakaan Rumah Pelangi tidak lagi digunakan, sehingga keberlanjutan program perlu dirancang lebih serius'],
  94, null, 417, 45, 5, 5, 5, 'draft'
),

(
  'guim-13', 13, 'GUIM 13', 'Kabupaten Pesawaran', 'Lampung', 'Juni 2023 - Juli 2024',
  'Kilaukan Asa Maknai Cerita', null, null,
  'GUIM 13 adalah program pengabdian masyarakat berbentuk community service selama satu bulan di bidang pendidikan dasar di daerah pelosok, dengan isu utama kekerasan seksual, intoleransi, perundungan, dan pemerataan pendidikan. Kegiatan aksi berlangsung 4 Januari - 2 Februari 2024 di Kabupaten Pesawaran, Provinsi Lampung, menjangkau 5 sekolah dasar di 4 kecamatan dengan 90 mahasiswa UI yang terlibat langsung. Kegiatan belajar mengajar berjalan Senin sampai Jumat, dilengkapi team teaching bersama guru serta kelas-kelas isu kontekstual untuk mencerdaskan tiga dosa besar pendidikan.',
  'Tagline "Kilaukan Asa Maknai Cerita" bermakna mimpi GUIM 13 untuk menjadi cahaya yang merepresentasikan awal perubahan bagi anak-anak dan masyarakat titik aksi, sekaligus menjadi cahaya bagi panitia dan pengajar melalui cerita yang dirajut dan dimaknai selama perjalanan bersama GUIM 13. Kabupaten Pesawaran dipilih lewat survei 0 dengan pertimbangan rata-rata lama sekolah 7,77 tahun, IPM 66,70, UKG 50,57, angka melek huruf 96,03, aksesibilitas 293 km (sekitar 6 jam via Merak-Bakauheni), serta konsiderasi bencana longsor, banjir, dan gempa.',
  ARRAY['GUIMO Tour dan GUIMO Ranger secara daring sebagai penuansaan rekrutmen panitia dan pengajar — 151 mahasiswa UI mendaftar','Survei 0: pemilihan Kabupaten Pesawaran berdasarkan indikator pendidikan, aksesibilitas, kriminalitas, dan risiko bencana','Survei 1: kunjungan langsung ke 16 sekolah potensial di 4 kecamatan (Tegineneng, Way Ratai, Negeri Katon, Way Khilau) untuk menentukan 5 sekolah sasaran','Survei 2: survei masyarakat dan stakeholder di 5 sekolah terpilih, sekaligus mencari rumah tinggal panitia dan pengajar selama satu bulan aksi','Grand Opening luring sebagai tanda dibukanya GUIM 13 secara resmi, dilanjutkan Welcoming Staff dan Musyawarah Kerja (Pleno)','Team building, pembekalan-pelatihan, dan pelantikan panitia serta pengajar','Gerakan Donasi Buku: lebih dari 1.000 buku terkumpul untuk sekolah di titik aksi'],
  ARRAY['Aksi mengajar di 5 SD Kabupaten Pesawaran: 4 Januari - 2 Februari 2024','Aksi Mengajar dan Team Teaching: KBM efektif sekitar tiga minggu, Senin sampai Jumat, menyesuaikan kurikulum sekolah bersama wali kelas','Teacher Visit dan Home Visit: kunjungan ke rumah wali kelas dan lebih dari 180 orang tua siswa','Bincang Guru: evaluasi gabungan pengajar dan guru tiap akhir pekan KBM dengan format 3P (progress, problem, plan)','Kelas informal isu kontekstual: Kelas Perundungan, Kelas Keberagaman, Kelas Otoritas Tubuh, dan Kelas Inspirasi','Program Tambahan Belajar di luar jam sekolah, fleksibel sesuai kesepakatan pengajar dan siswa','Pelatihan Guru bersama Gernastastaka bertema "Pembelajaran Matematika Konseptual" — diikuti 51 guru','Rumah Pelangi dan Pojok Baca: revitalisasi perpustakaan untuk meningkatkan minat baca siswa','Pembagian Laporan Belajar kualitatif kepada orang tua, dilanjutkan Bincang Orang Tua','Dekat di Titik Aksi (DEKSI): kegiatan panitia dan pengajar membaur bersama masyarakat, misalnya membantu warga di kebun','Festival Rakyat: pesta puncak bersama masyarakat dengan pertunjukan seni siswa dan lomba — melibatkan lebih dari 500 warga sekitar'],
  ARRAY['Penyusunan 5 Laporan Rekomendasi titik dan 1 Laporan Rekomendasi Umum dengan metode Participatory Rural Appraisal (PRA)','Audiensi laporan rekomendasi ke tiap sekolah sasaran, serta audiensi keberhasilan umum ke Pemerintah Kabupaten, Dinas Pendidikan, dan kecamatan','Publikasi teaser, after movie, dan Buku Antologi GUIM 13, serta liputan Tempo, Antara News, Jawa Pos, dan Medcom.id','Pendaftaran HKI untuk infografis dan video after movie GUIM 13','Grand Closing dan Rapat Pleno GUIM 13'],
  '[{"nama":"SDN 26 Tegineneng","kecamatan":"Tegineneng"},{"nama":"SDN 22 Negeri Katon","kecamatan":"Negeri Katon"},{"nama":"SDN 11 Way Khilau","kecamatan":"Way Khilau"},{"nama":"SDN 10 Way Ratai","kecamatan":"Way Ratai"},{"nama":"SDN 19 Way Ratai","kecamatan":"Way Ratai"}]'::jsonb,
  ARRAY['Kelas isu kontekstual "tiga dosa besar pendidikan": perundungan, keberagaman/intoleransi, dan otoritas tubuh','Kolaborasi Pelatihan Guru dengan Gernastastaka untuk materi Pembelajaran Matematika Konseptual','Kelas Otoritas Tubuh bersama Forum Anak Pesawaran (FORNASA)','Bincang Guru dengan format 3P (progress, problem, plan) sebagai rapat evaluasi mingguan bersama guru sekolah','Program Tambahan Belajar di luar jam sekolah yang waktunya disepakati langsung antara pengajar dan siswa','Dekat di Titik Aksi (DEKSI) dari divisi Public Relation untuk membaur bersama masyarakat','Gerakan Donasi Buku yang mengumpulkan lebih dari 1.000 buku untuk sekolah titik aksi'],
  ARRAY['151 mahasiswa UI mendaftar menjadi panitia atau pengajar; 90 di antaranya terlibat langsung di Pesawaran','100% panitia dan pengajar yang mengisi survei evaluasi merasakan kebermanfaatan GUIM dengan skor 3,95 dari 4','100% pengajar melaksanakan KBM di titik aksi selama tiga minggu pembelajaran','Menerbitkan 40 konten edukatif melalui Instagram dan website, serta berkolaborasi dengan 56 stakeholder','5 Laporan Rekomendasi titik dan 1 Laporan Rekomendasi Umum disusun dengan metode Participatory Rural Appraisal (PRA)','77% siswa SD sasaran pernah mengikuti kegiatan pembelajaran tambahan','100% sampel di 5 titik menyatakan kelas informal bermanfaat bagi perubahan semangat belajar dan pemahaman anak di luar ilmu formal','51 guru mengikuti pelatihan "Pembelajaran Matematika Konseptual" bersama Gernastastaka','3 perpustakaan direvitalisasi (SDN 26 Tegineneng, SDN 22 Negeri Katon, SDN 11 Way Khilau), 1 perpustakaan dialokasikan di bangunan desa (SDN 19 Way Ratai), dan 3 kelas dibuatkan pojok baca (SDN 10 Way Ratai)','40 peserta dan pengajar yang mengisi survei evaluasi berencana melanjutkan kegiatan di bidang sosial dan/atau pendidikan','Total dana terkumpul Rp204.000.000 (Dirmawa UI, dukungan Damri dan Paragon, serta merchandise dan open donation)'],
  ARRAY['Temuan: semangat belajar siswa sangat bervariasi antartitik, namun ada pola pengajaran yang konsisten menaikkannya — media pembelajaran kreatif, permainan seperti suit matematika, dan empati kepada murid yang butuh tempat bercerita','Temuan: guru wali kelas di semua titik dapat bekerja sama dengan pengajar — memberi ide dan menyediakan media pembelajaran, mencoba ice breaking ala GUIM, dan aktif mengikuti team teaching — meski di beberapa titik kehadiran guru masih kurang dirasakan','Rekomendasi Rumah Pelangi: perlu perawatan rutin secara fisik maupun administrasi peminjaman, pengembalian, dan peletakan buku agar tetap hidup','Rekomendasi Home Visit dan pertemuan wali murid-sekolah: diprioritaskan bagi siswa yang bermasalah secara akademik maupun sosial, agar hubungan sekolah dan orang tua lebih erat dan transparan','Rekomendasi metode pengajaran kreatif: gunakan permainan, objek di kelas atau boneka tangan, dan narasi/cerita saat memaparkan materi','Rekomendasi sosialisasi orang tua/wali: secara kelompok bila temuan berpola (mis. minimnya bimbingan belajar di rumah) dan secara individu untuk kasus spesifik seperti anak kelas 3 yang belum lancar membaca','Rekomendasi pelatihan guru: perluas ke sikap menghadapi siswa yang sedang bersedih, manajemen kelas, dan cara mengajar anak berkebutuhan khusus','GUIM 13 tidak melaksanakan monitoring & evaluation formal; hasil di bawah berasal dari laporan rekomendasi dan komunikasi lanjutan dengan guru serta orang tua murid','Tindak lanjut: siswa menunjukkan peningkatan motivasi belajar, terlihat dari kehadiran di sekolah dan meningkatnya kemampuan baca-tulis','Tindak lanjut: orang tua lebih aktif memberi dukungan belajar di rumah dan hadir dalam kegiatan sekolah'],
  90, null, 372, 51, 5, null, 4, 'draft'
),

(
  'guim-14', 14, 'GUIM 14', 'Kabupaten Blora', 'Jawa Tengah', 'Juni 2024 - Juli 2025',
  'Bergerak Berbagi Inspirasi', null, null,
  'GUIM 14 adalah program pengabdian masyarakat berbentuk community service selama satu bulan di bidang pendidikan dasar di daerah pelosok. Aksi dilaksanakan 6 Januari - 1 Februari 2025 di Kabupaten Blora, Provinsi Jawa Tengah, menjangkau 6 sekolah dasar di 5 kecamatan. Kegiatan belajar mengajar berjalan Senin sampai Jumat dengan mekanisme team teaching bersama guru. Di luar kelas formal, panitia menyusun kelas informal berdasarkan hasil need assessment tiap titik: "Semua Aku Sayangi" (non-bullying dan toleransi), "Kenali Tubuhmu" (anti kekerasan seksual dan PHBS), Kelas Inspirasi (pengenalan cita-cita), serta kelas eksplorasi bertema kebersihan lingkungan, literasi-numerasi, dan literasi digital.',
  'Tema "Bergerak Berbagi Inspirasi" terdiri dari tiga kata yang bermakna sendiri-sendiri tetapi saling menguatkan ketika disatukan — sebuah ajakan kolaborasi kepada semua pihak untuk peduli terhadap kondisi aktual pendidikan di Indonesia, sekaligus wadah bagi mahasiswa UI dan masyarakat titik aksi untuk saling memberi dan menerima kebermanfaatan. Kabupaten Blora dipilih lewat survei 0 dengan pertimbangan APK SD 104,7, APM SMP 24,98, Indeks Pembangunan Umum 70,63, dan rata-rata lama sekolah 7,08 tahun.',
  ARRAY['GUIMO Discover secara daring sebagai penuansaan rekrutmen panitia dan pengajar — 167 mahasiswa UI mendaftar','Survei 0: pemilihan Kabupaten Blora berdasarkan indikator partisipasi sekolah dan rata-rata lama sekolah','Survei 1: satu minggu penuh mengunjungi 18 sekolah di 8 kecamatan (Kunduran, Ngawen, Todanan, Jiken, Sambong, Bogorejo, Randublatung, Banjarejo) serta audiensi dengan Dinas Pendidikan Kabupaten Blora, kecamatan, dan desa','Survei 2: pengumpulan data kebutuhan spesifik sekolah, audiensi program yang lebih rinci ke sekolah dan masyarakat desa, serta pencarian rumah panitia dan pengajar','Grand Opening luring, Welcoming Staff, dan Musyawarah Kerja (Pleno)','Team building, pembekalan-pelatihan, dan pelantikan panitia serta pengajar'],
  ARRAY['Aksi mengajar di 6 SD Kabupaten Blora: 6 Januari - 1 Februari 2025','Aksi Mengajar dengan team teaching: KBM menyesuaikan kurikulum sekolah dan materi terakhir dari wali kelas','Kelas informal hasil need assessment: kelas pendidikan toleransi, kelas otoritas tubuh, Kelas Inspirasi, dan kelas eksplorasi — terlaksana tiga kali setiap minggu','Program Tambahan Belajar di luar jam sekolah, fleksibel sesuai kesepakatan pengajar dan siswa','Rumah Pelangi: revitalisasi perpustakaan sebagai sarana pendukung belajar','Teacher Visit dan Home Visit ke rumah wali kelas dan orang tua murid','Pelatihan Guru bertema metode pembelajaran kreatif','Bincang Guru: evaluasi gabungan pengajar dan guru di masing-masing titik','Pembagian Laporan Belajar kepada orang tua, dilanjutkan Bincang Orang Tua satu kali di tiap titik','Dekat di Titik Aksi (DEKSI): kegiatan panitia dan pengajar bersama masyarakat','Festival Rakyat: penutup seluruh rangkaian GUIM 14 di titik aksi'],
  ARRAY['Audiensi laporan rekomendasi satu kali di masing-masing titik ke sekolah sasaran, serta audiensi keberhasilan umum ke Pemerintah Kabupaten Blora','Publikasi liputan di inews.id, edukasi.okezone.com, dan jateng.antaranews.com; infografis dan after movie GUIM 14 didaftarkan HKI','Grand Closing dan Rapat Pleno GUIM 14','Monitoring and Evaluation: 27-31 Juli 2025, enam bulan setelah masa aksi','Penyerahan laporan rekomendasi lanjutan hasil monev kepada Dinas Pendidikan Kabupaten Blora dan masing-masing sekolah titik aksi'],
  '[{"nama":"SDN 3 Bogorejo","kecamatan":"Bogorejo"},{"nama":"SDN Gayam","kecamatan":"Bogorejo"},{"nama":"SDN Dalangan","kecamatan":"Todanan"},{"nama":"SDN 2 Tawangrejo","kecamatan":"Kunduran"},{"nama":"SDN 3 Sumberjo","kecamatan":"Randublatung"},{"nama":"SDN 2 Bleboh","kecamatan":"Jiken"}]'::jsonb,
  ARRAY['Kelas informal dirancang dari hasil need assessment tiap titik, bukan seragam antartitik — melahirkan kelas eksplorasi bertema kebersihan lingkungan, literasi-numerasi, dan literasi digital','Kelas "Semua Aku Sayangi" sebagai materi non-bullying dan toleransi','Kelas "Kenali Tubuhmu" sebagai materi anti kekerasan seksual dan PHBS','Pelatihan Guru bertema metode pembelajaran kreatif bersama Komunitas Guru Belajar Nusantara','Rumah Pelangi dengan sistem peminjaman buku dan duta rumah pelangi agar program tetap hidup setelah aksi selesai','Program Tambahan Belajar yang jadwalnya disepakati langsung antara pengajar dan siswa','Dekat di Titik Aksi (DEKSI) dari divisi Public Relation untuk membaur bersama masyarakat'],
  ARRAY['167 mahasiswa UI mendaftar menjadi panitia atau pengajar GUIM 14','98,46% pengajar melaksanakan seluruh kegiatan aksi mengajar selama 3 minggu periode aksi','97,5% guru di sekolah titik aksi menilai program kerja GUIM 14 bermanfaat bagi murid (skor kepuasan minimal 4 dari 6)','97,5% guru merasa dilibatkan dalam program kerja GUIM 14 (skor kepuasan minimal 4 dari 6)','86,97% siswa SD sasaran pernah mengikuti kegiatan pembelajaran tambahan','Kelas informal terlaksana tiga kali setiap minggu selama periode aksi','Menerbitkan 22 konten edukatif melalui Instagram dan website, serta berkolaborasi dengan 54 stakeholder','Bincang orang tua terlaksana satu kali di masing-masing titik aksi','Angkatan pertama sejak GUIM 12 yang kembali menggelar monitoring & evaluation formal — 27-31 Juli 2025, dengan laporan rekomendasi lanjutan ke Dinas Pendidikan Kabupaten Blora','Total dana terkumpul Rp231.005.894 (Dirmawa UI serta sponsor MIND ID, PT Titis Sampurna, BRI, Chipsin, Paragon, Agatis, Zebra, Perkebunan Nusantara, My Fund Action, Damri, dan Jasa Marga)'],
  ARRAY['Temuan: metode pembelajaran yang melibatkan diskusi kelompok, permainan edukatif, dan suasana menyenangkan terbukti efektif menaikkan partisipasi dan semangat belajar serta mengurangi kebosanan siswa','Temuan: siswa di semua sekolah umumnya bersemangat belajar dan punya rasa ingin tahu besar — modal baik untuk pendidikan yang lebih interaktif dan berbasis minat','Temuan: terdapat ketimpangan signifikan kemampuan literasi dan numerasi antarsiswa di semua sekolah','Temuan: minat baca cukup tinggi di beberapa sekolah, tetapi perpustakaan yang kurang terawat dan minimnya variasi buku menghambat siswa membaca di luar buku pelajaran','Temuan: sarana dan prasarana yang sudah ada di beberapa sekolah belum dimanfaatkan secara maksimal','Temuan: keterlibatan orang tua dalam mendampingi belajar di rumah berdampak positif pada semangat dan kemampuan siswa','Rekomendasi: pelatihan guru soal strategi pembelajaran diferensiatif, inovasi metode menyenangkan, manajemen kelas, dan media pembelajaran kreatif','Rekomendasi: peningkatan sarana dan prasarana — media pembelajaran interaktif, perbaikan ruang kelas dan perpustakaan, variasi buku bacaan, serta perbaikan akses jalan menuju sekolah','Rekomendasi: pelibatan orang tua secara berkelanjutan lewat forum komunikasi wali murid, konsultasi guru-wali murid, dan pelatihan pendampingan belajar di rumah','Monev Juli 2025: beberapa sekolah menunjukkan peningkatan kreativitas guru lewat penggunaan ice breaking tepuk dan metode pembelajaran kreatif','Monev Juli 2025: program Rumah Pelangi berlanjut di beberapa sekolah — perawatan rutin, sistem peminjaman buku, dan pembaruan duta rumah pelangi; satu sekolah bahkan mengadaptasinya menjadi kegiatan literature review','Monev Juli 2025: peningkatan kemampuan calistung terutama di kelas kecil, serta perubahan sikap anak yang lebih sadar terhadap bercandaan kepada teman','Monev Juli 2025: orang tua lebih sadar akan pendidikan dan bakat anak — jumlah orang tua yang mendaftarkan anak ke tempat les meningkat','Monev Juli 2025: guru melaporkan peningkatan semangat belajar, rasa percaya diri, waktu fokus anak, kesadaran kebersihan lingkungan, kedisiplinan guru, serta pengetahuan anak tentang jenis pekerjaan dan cita-cita','Monev Juli 2025: terjadi perubahan stigma masyarakat tentang mahasiswa kota yang dianggap tidak bisa bersosialisasi, terlihat dari kedekatan panitia dan pengajar dengan warga di 6 titik aksi','Monev Juli 2025: terdapat sekolah yang melanjutkan program tambahan belajar untuk siswa yang membutuhkan'],
  104, null, 441, 51, 6, null, 5, 'draft'
);
